---
- hosts: servers
  remote_user: root
  gather_facts: true
  become: true

  tasks:
    - include_tasks: ./php.yml
    - include_tasks: ./apache.yml

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
